#!/bin/bash

DURATIONS="1m\n10m\n30m\n45m\n1h\n90m\n2h\n4h"

SELECTED_DURATION=$(echo -e "$DURATIONS" | tofi -c $XDG_CONFIG_HOME/tofi/config --include "$XDG_CACHE_HOME/wal/colors-tofi" --prompt-text "$(date "+%I:%M %p") + " --height 200 --width 200)

if [[ -n "$SELECTED_DURATION" ]]; then
    REMINDER_NAME=$(echo "" | tofi -c $XDG_CONFIG_HOME/tofi/config --include "$XDG_CACHE_HOME/wal/colors-tofi" --include "$XDG_CONFIG_HOME/scripts/remind-tofi" --prompt-text "in $SELECTED_DURATION : " --height 40 --width 400)
fi

if [[ -n "$REMINDER_NAME" ]]; then
    (sleep "$SELECTED_DURATION" && notify-send "Reminder:" "$REMINDER_NAME" -h int:x-hyprnotify-font-size:15 -h string:x-hyprnotify-color:$(sed -n '12p' "$XDG_CACHE_HOME/wal/colors" | tr -d '\n') -t 10000) & disown
    notify-send "Reminder Set:" "$REMINDER_NAME: $SELECTED_DURATION" -h int:x-hyprnotify-font-size:15 -h string:x-hyprnotify-color:$(sed -n '12p' "$XDG_CACHE_HOME/wal/colors" | tr -d '\n') -t 2500
fi

