#!/bin/bash

# Prepend "Assign Random" to the list of wallpapers, then pass it to tofi
SELECTED=$(echo -e "Assign Random\n$(ls $HOME/Pictures/wallpapers)" | tofi -c $HOME/.config/tofi/config --include "$HOME/.cache/wal/colors-tofi")

# Call theme.sh with the selected option
if [ "$SELECTED" == "Assign Random" ]; then
  $HOME/.config/hypr/theme.sh "random"
else
  $HOME/.config/hypr/theme.sh "$SELECTED"
fi
