#!/bin/bash

# Call theme.sh with the output of tofi command as a parameter
$HOME/.config/hypr/theme.sh "$(ls $HOME/Pictures/wallpapers | tofi -c $HOME/.config/tofi/config --include "$HOME/.cache/wal/colors-tofi")"
