#!/bin/bash

curl -sS http://time.lan/data | jq -r 'sort_by(.today_duration) | reverse | .[0:5] | .[] | "\(.window_class)|\(.today_duration / 60 | floor)"' | while IFS='|' read -r class duration; do
    printf "%-30s %s minutes\n" "$class" "$duration"
done
