-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1200@59.95",
    position = "-1920x0",
    scale    = 1,
    vrr      = 0,
})

hl.monitor({
    output   = "DP-2",
    mode     = "1920x1080@143.98",
    position = "0x0",
    scale    = 1,
    vrr      = 0,
})

hl.monitor({
    output   = "DP-3",
    mode     = "1920x1080@60.00",
    position = "1920x0",
    scale    = 1,
    vrr      = 0,
})

-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/

hl.workspace_rule({
    workspace = 1,
    monitor = "HDMI-A-1",
    persistent = true,
    default = true
})

hl.workspace_rule({
    workspace = 2,
    monitor = "HDMI-A-1",
    persistent = true,
})

hl.workspace_rule({
    workspace = 3,
    monitor = "DP-2",
    persistent = true,
    default = true
})

hl.workspace_rule({
    workspace = 4,
    monitor = "DP-2",
    persistent = true,
})

hl.workspace_rule({
    workspace = 5,
    monitor = "DP-3",
    persistent = true,
    default = true
})

hl.workspace_rule({
    workspace = 6,
    monitor = "DP-3",
    persistent = true,
})

hl.workspace_rule({
    workspace = 7,
    monitor = "DP-3",
    persistent = true,
})

hl.workspace_rule({
    workspace = 8,
    monitor = "DP-3",
    persistent = true,
})

hl.workspace_rule({ workspace = "special:media" })
hl.workspace_rule({ workspace = "special:info", on_created_empty = "[float; size 35% 50.2%; center] kitty now" })
hl.workspace_rule({ workspace = "special:music", on_created_empty = "[float; size 50% 60%; center] kitty spotify_player" })
hl.workspace_rule({ workspace = "special:python", on_created_empty = "[float; size 50% 50%; center] kitty python3" })
hl.workspace_rule({ workspace = "special:volume", on_created_empty = "[float; size 60% 80%; center] pavucontrol -t 1" })
hl.workspace_rule({ workspace = "special:anki", on_created_empty = "anki" })

-- Startup Exec

-- source = ~/.config/hypr/exec.conf -> requires manual conversion
local exec = require("exec")
-- TODO: convert ~/.config/hypr/exec.conf to .lua and use require()

-- Enviroment Variables

-- source = ~/.config/hypr/env.conf -> requires manual conversion
local env = require("env")
-- TODO: convert ~/.config/hypr/env.conf to .lua and use require()

-- Window Rules

-- source = ~/.config/hypr/windowRules.conf -> requires manual conversion
local windowRules = require("windowRules")
-- TODO: convert ~/.config/hypr/windowRules.conf to .lua and use require()

-- Keybinds

-- source = ~/.config/hypr/keybinds.conf -> requires manual conversion
local keybinds = require("keybinds")
-- TODO: convert ~/.config/hypr/keybinds.conf to .lua and use require()

-- Color Theme for config

-- source = ~/.cache/wal/colors-hyprland.conf -> requires manual conversion
local colors = dofile(os.getenv("HOME") .. "/.cache/wal/colors-hyprland.lua")
-- TODO: convert ~/.cache/wal/colors-hyprland.conf to .lua and use require()

-- Config

-- For all categories, see https://wiki.hyprland.org/Configuring/Variables/

hl.config({
    general = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        border_size = 2,
        gaps_in = 4,
        gaps_out = 8,
        layout = "dwindle",
        allow_tearing = true,
        col = {
            active_border = { colors = { colors.color11, colors.color4 }, angle = 45 },
            inactive_border = "rgb(595959)",
        },
    },
})

hl.config({
    decoration = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        rounding = 1,
        active_opacity = 0.95,
        inactive_opacity = 0.85,
        fullscreen_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 10,
            render_power = 2,
            color = "rgba(1a1a1aee)",
        },
        dim_special = 0.2,
        blur = {
            enabled = true,
            size = 4,
            passes = 2,
            ignore_opacity = true,
            new_optimizations = true,
            special = true,
        },
    },
})

hl.config({
    animations = {
        -- See https://wiki.hyprland.org/Configuring/Animations/ for more
        enabled = true,
        -- animation=NAME,ONOFF,SPEED,CURVE
    },
})

hl.curve("myBezier", {
    type = "bezier",
    points = {
        { 0.05, 0.9 },
        { 0.1,  1.05 },
    },
})

hl.animation({ leaf = "layers", enabled = true, speed = 2, bezier = "default", style = "popin 70%" })
hl.animation({ leaf = "windows", enabled = true, speed = 4, bezier = "myBezier", style = "popin 70%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 4, bezier = "default", style = "popin 70%" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 4, bezier = "myBezier", style = "slide" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 4, bezier = "default", style = "slidevert" })
hl.config({
    input = {
        kb_layout = "us",
        touchpad = {
            natural_scroll = false,
        },
        sensitivity = 0,
        accel_profile = "flat",
        follow_mouse = 1,
        focus_on_close = 1,
    },
})

hl.config({
    gestures = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
    },
})

hl.config({
    dwindle = {
        -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
        -- pseudotile = true
        preserve_split = true,
    },
})

hl.config({
    master = {
        -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
        -- new_is_master = true
    },
})

hl.config({
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        -- vfr = true
        -- vrr = 2
        mouse_move_enables_dpms = true,
        key_press_enables_dpms = true,
        animate_manual_resizes = true,
        animate_mouse_windowdragging = true,
        enable_swallow = false,
        swallow_regex = "^(kitty)$",
        focus_on_activate = false,
        close_special_on_empty = true,
        -- new_window_takes_over_fullscreen = 0
        font_family = "Delugia Mono",
    },
})

hl.config({
    ecosystem = {
        no_update_news = true,
        no_donation_nag = true,
    },
})

hl.config({
    binds = {
        workspace_center_on = 1,
    },
})

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

-- opengl {

--     force_introspection = 1

-- }

hl.config({
    render = {
        ctm_animation = 1,
        direct_scanout = 1,
    },
})

hl.config({
    debug = {
        disable_logs = false,
        enable_stdout_logs = true,
    },
})
