#!/bin/bash

WALLPAPERS="$HOME/Pictures/wallpapers"

# if "random" is passed, select a random theme folder
if [ "$1" == "random" ]; then
  themes=($WALLPAPERS/*)
  rand_theme=${themes[RANDOM % ${#themes[@]}]}
  theme=$(basename "$rand_theme")
else
  theme=$1
fi

# locate theme images, find proper file extensions 
function find_image {
  local theme=$1
  local img_num=$2
  local base_path="$WALLPAPERS/$theme/$img_num"

  for ext in jpg png jpeg gif; do
    if [[ -f "$base_path.$ext" ]]; then
      echo "$base_path.$ext"
      return 0
    fi
  done

  echo "Error: No image found."
  return 1
}

# adjust the theme variable for image finding
image1=$(find_image $theme 1)
image2=$(find_image $theme 2)
image3=$(find_image $theme 3)

hyprctl hyprpaper unload all

# set wallpapers if they were found
[ "$image1" != "Error: No image found." ] && hyprctl hyprpaper preload "$image1" 
[ "$image2" != "Error: No image found." ] && hyprctl hyprpaper preload "$image2" 
[ "$image3" != "Error: No image found." ] && hyprctl hyprpaper preload "$image3" 


hyprctl hyprpaper wallpaper "DP-2, $image1"
hyprctl hyprpaper wallpaper "DP-3, $image2"
hyprctl hyprpaper wallpaper "HDMI-A-1, $image3"


# generate gtk theme
wpg -s $image1 -n


# generate pywal scheme
[ "$image1" != "Error: No image found." ] && wal -q -i "$image1" 

# run pywal scripts
pywalfox update
sh $XDG_CONFIG_HOME/dunst/wal.sh
sh $XDG_CONFIG_HOME/spicetify/Themes/Pywal/update-colors.sh 

pywal-discord -t default -p /home/badtz/.config/vesktop/themes/
$XDG_CONFIG_HOME/wpg/wp_init.sh

# notify theme
notify-send "Theme set to" $theme -h string:x-hyprnotify-color:$(sed -n '12p' "$XDG_CACHE_HOME/wal/colors" | tr -d '\n') -t 2000

# store wallpapers in config file
echo "preload = $image1" > "$XDG_CONFIG_HOME/hypr/hyprpaper.conf"
echo "wallpaper = DP-2, $image1" >> "$XDG_CONFIG_HOME/hypr/hyprpaper.conf"
echo "preload = $image2" >> "$XDG_CONFIG_HOME/hypr/hyprpaper.conf"
echo "wallpaper = DP-3, $image2" >> "$XDG_CONFIG_HOME/hypr/hyprpaper.conf"
echo "preload = $image3" >> "$XDG_CONFIG_HOME/hypr/hyprpaper.conf"
echo "wallpaper = HDMI-A-1, $image3" >> "$XDG_CONFIG_HOME/hypr/hyprpaper.conf"

# remove file generated by wpg
rm ~/.fehbg 
