import = ["/home/badtz/.cache/wal/colors-alacritty.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "firacode"
style = "Regular"

[font.offset]
x = 0
y = 0

[shell]
program = "/bin/fish"

[window]
dynamic_title = true
opacity = 1

[window.padding]
x = 4
y = 4
